version: "3.8"

networks:
  authentik:
    driver: bridge

volumes:
  database:
  redis:

services:
  postgresql:
    image: ${ECR_REGISTRY}/authentik-postgres:${AUTHENTIK_TAG}
    container_name: authentik-postgresql
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - authentik

  redis:
    image: ${ECR_REGISTRY}/authentik-redis:${AUTHENTIK_TAG}
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - authentik

  server:
    image: ${ECR_REGISTRY}/authentik-server:${AUTHENTIK_TAG}
    container_name: authentik-server
    restart: unless-stopped
    command: server
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    ports:
      - "${COMPOSE_PORT_HTTP}:${COMPOSE_PORT_HTTP}"
      - "${COMPOSE_PORT_HTTPS}:${COMPOSE_PORT_HTTPS}"
    depends_on:
      postgresql:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - authentik

  worker:
    image: ${ECR_REGISTRY}/authentik-worker:${AUTHENTIK_TAG}
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    depends_on:
      postgresql:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - authentik

