server {
    listen 80;
    server_name authentik.srespace.tech;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name authentik.srespace.tech;

    ssl_certificate /etc/nginx/certs/authentik.crt;
    ssl_certificate_key /etc/nginx/certs/authentik.key;

    location / {
        proxy_pass http://localhost:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

