name: CI/CD - Build, Push, Deploy Authentik

on:
  push:
    branches: [main]

env:
  DOCKER_USER: noletengine
  VAULT_ADDR: http://192.168.0.116:8200

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Vault using Token
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          export VAULT_TOKEN=$VAULT_TOKEN
          vault token lookup || exit 1

      - name: Fetch Secrets from Vault and Export to GITHUB_ENV
        run: |
          secrets=$(vault kv get -format=json secret/Dev-secret/authentik | jq -r '.data.data')
          echo "$secrets" | jq -r 'to_entries[] | "echo \(.key)=\(.value) >> $GITHUB_ENV"' | bash

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Authentik Server
        run: |
          docker build -f Dockerfile.server -t $DOCKER_USER/authentik-server:latest .
          docker push $DOCKER_USER/authentik-server:latest

      - name: Build & Push Authentik Worker
        run: |
          docker build -f Dockerfile.worker -t $DOCKER_USER/authentik-worker:latest .
          docker push $DOCKER_USER/authentik-worker:latest

      - name: Deploy Using Docker Compose
        run: |
          docker compose pull
          docker compose up -d --remove-orphans

